### ISSUE TITLE
italics not being exported

### ISSUE THREAD

**Issue by murtaza52** [larstvei/ox-gfm#2] opened 2014-12-16 05:56 UTC
Hi Lars,

Thanks for the backend !

When I try exporting from orgmode which have italics - /hello this is in italics/ - it doesnt show up in italics in the markdown. Can you please check ?

Thanks,
Murtaza

**Comment by larstvei** [comment] 2015-01-08 21:56
Since I could not reproduce the bug I'll close the issue.

- Lars

**Closed by larstvei** 2015-01-08 21:56 UTC
